DROP TABLE demo

CREATE TABLE RECIBO (
ID_NF INT NOT NULL,
ID_ITEM INT NOT NULL,
COD_PROD INT NOT NULL,
VALOR_UNIT FLOAT (4) NOT NULL,
QUANTIDADE VARCHAR (2) NOT NULL,
DESCONTO CHAR (2) NULL );

INSERT INTO RECIBO ( ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO)
VALUES ("1", "1", "1", "25,00", "10", "5");


INSERT INTO RECIBO ( ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO)
VALUES ("1", "2", "2", "13,50", "3", "0");

INSERT INTO RECIBO ( ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO)             
VALUES ("2", "1", "3", "15,00", "4", "0");

INSERT INTO RECIBO ( ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO)
VALUES ("2", "2", "4", "10,00", "5", "0");

 INSERT INTO RECIBO ( ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO)     
VALUES ("3", "1", "1", "25,00", "5", "0");

INSERT INTO RECIBO ( ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO)
VALUES ("3", "2", "4", "10,00", "4", "0");

 INSERT INTO RECIBO ( ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO)
VALUES ("4", "1", "5", "30,00", "10", "15");

INSERT INTO RECIBO ( ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO)
VALUES ("4", "2", "4", "10,00", "12", "5");

INSERT INTO RECIBO ( ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO)
VALUES ("5", "1", "3", "15,00", "3", "0");

INSERT INTO RECIBO ( ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO)
VALUES("5", "2", "5", "30,00", "6", "0");

INSERT INTO RECIBO ( ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO)
VALUES ("6", "1", "1", "25,00", "22", "15");

INSERT INTO RECIBO ( ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO)
VALUES ("6", "2", "3", "15,00", "25", "20");

INSERT INTO RECIBO ( ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO)
VALUES ("7", "1", "1", "25,00", "10", "3");

INSERT INTO RECIBO ( ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO)
VALUES ("7", "2", "2", "13,50", "10", "4");

update RECIBO SET desconto = "0"
WHERE desconto = ""

SELECT * FROM RECIBO

SELECT * FROM RECIBO WHERE DESCONTO = "NULL"
SELECT * FROM RECIBO WHERE DESCONTO 

CREATE TABLE DESCONTO
( DSC INT NOT NULL,
 valor float NOT NULL,
 PRIMARY KEY (dsc)
 )

INSERT INTO desconto (dsc, valor)
VALUES
(1,"5%"),
(2,"10%"),
(3,"15%"),
(4,"20%"),
(5,"25%"),
(6,"30%"),
(7,"35%"),
(8,"40%"),

SELECT * FROM DESCONTO

CREATE TABLE PRODUTO
(id_produto INT NOT NULL PRIMARY KEY,
 valor_unit varchar (100) NOT NULL,
 qtd varchar (1000) not NULL, 
 dsc int not NULL,
 FOREIGN KEY (dsc) REFERENCES Desconto (dsc)
 );
 
 insert into produto (id_produto, valor_unit, qtd, dsc)
 VALUES ("1", "10,00", "3", "2%")
 
 INSERT INTO produto (id_produto, valor_unit, qtd, dsc)
 VALUES ("2", "15,00", "4", "3%")
 
 INSERT INTO produto (id_produto, valor_unit, qtd, dsc)
 VALUES ("3", "35,00", "5", "4%")
 
 INSERT INTO produto (id_produto, valor_unit, qtd, dsc)
 VALUES ("4", "32,00", "6", "5%")

SELECT * from PRODUTO


